module laff
    using LinearAlgebra
    include("vecvec/copy.jl")
    include("vecvec/scal.jl")
    include("vecvec/axpy.jl")
    include("vecvec/dot.jl")
    include("vecvec/norm2.jl")
    include("util/zerov.jl")
    include("util/onev.jl")
    include("vecvec/dots.jl")
    include("matvec/gemv.jl")
    include("matvec/ger.jl")
    include("vecvec/invscal.jl")
    include("matvec/trsv_lnn.jl")
    include("matvec/trsv_lnu.jl")
    include("matvec/trsv_ltu.jl")
    include("matvec/trsv_unn.jl")
    include("matvec/trsv_unu.jl")
    include("matvec/trsv_utn.jl")
    include("matvec/trsv.jl")
    include("matmat/trsm_lnu.jl")
    include("matmat/trsm_ltu.jl")
    include("matmat/trsm_unn.jl")
    include("matmat/trsm_utn.jl")
    include("matvec/trsm.jl")

end
